18F/epa-notice

- manifest.yml
We'll need to figure out manifest inheritance for the host name later
> Use consistent app names across envs

- notice_and_comment/settings/base.py
- notice_and_comment/settings/prod.py
Goes with https://github.com/18F/regulations-site/pull/136.
> Namespace attachment-related settings.

- cf-startup.sh
- manifest_base.yml
- requirements.txt
Attn @cmc333333 
To be reviewed after demo
> Use cors helper

- notice_and_comment/static/regulations/css/less/variables.less
For #69 
My naming conventions are a little questionable so if someone has a better suggestion I'm open to hear it.
> adding color variables

- notice_and_comment/static/regulations/css/less/comment-custom.less
- notice_and_comment/static/regulations/css/less/module/custom.less
- notice_and_comment/static/regulations/css/less/variables.less
Fixing #55 and #69 and done in conjunction with [168](https://github.com/18F/regulations-site/pull/168) on -site.
> Bringing styles back to notice and comment

- cf-startup.sh
- notice_and_comment/settings/base.py
- requirements.txt
Depends on https://github.com/18F/regulations-site/pull/183.
> Fetch wkhtmltox on deploy.

- .cfignore
- .gitignore
- README.md
> Document local setup; update ignore rules.

- README.md
- requirements.txt
> Replace 18F references to eregs.

- manifest_base.yml
> Fetch wkhtmltox on worker.

- .about.yml
Following the template at https://github.com/18F/about_yml
> Add initial .about.yml file (for 18F Team API)

- notice_and_comment/static/regulations/css/less/module/drawer-custom.less
The N&C pilot specific colors to go with this PR on site: https://github.com/eregs/regulations-site/pull/220
> ToC tab styles

- notice_and_comment/static/regulations/css/less/module/drawer-custom.less
removing some extra styles that exist in -site and don't need to be duplicated here.
> removing duplicate code (exists in -site)

- notice_and_comment/static/regulations/css/less/module/drawer-content-custom.less
This exists in -site and doesn't need to be here.
> removing duplicate table of contents code

- notice_and_comment/static/regulations/css/less/module/drawer-custom.less
Goes with eregs/regulations-site#238
> moving colors around for regulations-site#238

- notice_and_comment/settings/base.py
As we aren't parsing this out yet, but would like to start styling, this adds
some intro data (pulled from a recent EPA proposal)
The complement to eregs/regulations-site#244
> Mock rule intro data

- notice_and_comment/static/regulations/css/less/comment-custom.less
> css button change for eregs/regulations-site#281

- notice_and_comment/static/regulations/css/less/typography-custom.less
fixes #188 
This gives proper vertical margins to headers and goes with eregs/regulations-site#293 to solve #188.
> adjusting header margins

- notice_and_comment/static/regulations/css/less/mixins.less
goes with eregs/regulations-site#292
> removing font-style from bold

- notice_and_comment/templates/regulations/comment-additional-info.html
Tasks remaining:
Goes with https://github.com/eregs/regulations-site/pull/300
> [WIP] Prototype custom form fields.

- notice_and_comment/templates/regulations/comment-disclaimer.html
* Add template override for disclaimer text
* Add toggles for disclaimer sections
Goes with https://github.com/eregs/regulations-site/pull/305.
> Add custom disclaimer text.

- notice_and_comment/templates/regulations/comment-additional-info.html
Goes with https://github.com/eregs/regulations-site/pull/314.
> Use field options from template context.

- notice_and_comment/templates/regulations/comment-additional-info.html
- notice_and_comment/templates/regulations/comment-disclaimer.html
Changes to the disclaimer template file specific to this reg (classes added, header types changed)
for #246 but requires styles from a PR on -site.
> Comment Review Disclaimers

- deploy.sh
- manifest_base.yml
- manifest_prod.yml
* Add live url
* Increase app scale _after_ spinning down previous instances (so we don't hit
our memory limit)
> Production deployment updates

- notice_and_comment/templates/regulations/comment-additional-info.html
Goes with https://github.com/eregs/regulations-site/pull/343.
> Update comment form markup.

- notice_and_comment/templates/regulations/main-header.html
> removing about from header

- notice_and_comment/static/regulations/css/less/comment-custom.less
- notice_and_comment/static/regulations/css/less/typography-custom.less
- notice_and_comment/templates/regulations/main-header.html
> CFR style changes

- notice_and_comment/templates/regulations/comment-disclaimer.html
Disclaimer template for Review page cleanup: remove ids and data attributes for toggling, include show less toggle markup.
Relies on CSS/JS changes on eregs/regulations-site#352
> Clean template for Review disclaimer show more/less toggles

- notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less
- notice_and_comment/templates/regulations/nc-homepage.html
Expandable section is closed by default, upon click will open.
> Homepage expandable section

- notice_and_comment/templates/regulations/comment-additional-info.html
See eregs/regulations-site#354
> Align template with JS logic

- README.md
- requirements.txt
Also removes Quantified Code badge; it wasn't accurate
Partial fulfillment of 18F/Infrastructure#629
> Bump library versions. Add gemnasium badge

- notice_and_comment/templates/regulations/nc-homepage.html
Fixes #320 
Bill's proposed changes.
> Homepage content updates

- notice_and_comment/templates/regulations/comment-disclaimer.html
Fixes #321 
Just pluralizing a word.
> Submit confirmation change

- notice_and_comment/templates/regulations/nc-homepage.html
> Additional submissions link on homepage

- .codeclimate.yml
- .travis.yml
- README.md
- notice_and_comment/settings/base.py
- notice_and_comment/settings/prod.py
Bandit is a static security analyzer.
Code Climate and Quantified Code are static code quality analyzers.
In service of #332
> Add bandit, badges

- notice_and_comment/templates/regulations/nc-homepage.html
- notice_and_comment/urls.py
Depends on https://github.com/eregs/regulations-site/pull/398
> Add dynamic data to homepage

- notice_and_comment/static/regulations/css/less/comment-custom.less
- notice_and_comment/static/regulations/css/less/module/drawer-custom.less
- notice_and_comment/static/regulations/css/less/module/note-custom.less
- notice_and_comment/templates/regulations/comment-additional-info.html
- notice_and_comment/templates/regulations/comment-disclaimer.html
**General**
- Drawer header ordering colors
**Footnotes**
- Set positioning on anchor tag instead of icon so it is focusable
**Review page**
- Set `<legend>` on form, correct some labels
- Set correct order on statement headings
- Checkbox `id` to match label `for`
--
Relies on: eregs/regulations-site#408
> Accessibility Updates

- notice_and_comment/settings/prod.py
- notice_and_comment/templates/regulations/main-header.html
Sending info to GSA. Also fixes a template bug.
Resolves #364
> Activate DAP

- notice_and_comment/static/regulations/css/less/typography-custom.less
> swapping serifs and non-serifs

- notice_and_comment/templates/regulations/comment-disclaimer.html
> Review page polish

- .cfignore
- README.md
* Fix some issues with cfignore
* Fix some references in the README
> Two small tweaks

- manifest_prod.yml
For #389.
Doesn't quite resolve the issue, as we need support from usa.gov
> Add www. as a host in production

- manifest_dev.yml
> Remove auth on demo for now

- notice_and_comment/settings/base.py
- notice_and_comment/urls.py
Also some minor whitespace tweaks for flake8 compliance.
> Add ability to disable search engine indexing via environment variable.

- eregs_extensions/epa_regparser/term_defs/__init__.py
- eregs_extensions/setup.py
- requirements.txt
Fixes <https://github.com/18F/eregs-platform/issues/28>.
> Add term definitions for “CROMERR Costs”.

- notice_and_comment/settings/prod.py
For getting better marks
Resolves #419
> Add some cookie security settings in prod

- notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less
- notice_and_comment/templates/regulations/nc-homepage.html
> adding privacy policy link to homepage footer

- .about.yml
- README.md
- compliance/component.yaml
- notice_and_comment/templates/regulations/nc-homepage.html
- system-security-plan.yml
* Documentation updates
* Travis
* Gemnasium
* Code Climate
* Quantified Code
Part of #426
> Replace references for static analysis tools
