deploy.sh

This should be rolled back after issue #23 is resolved.

Temporarily push worker without autopilot.

---

README.md
notice_and_comment/settings/base.py

While we work on generating this data automatically, provide some mock data
related to 27 CFR 478 @ 2012-13762. Note that the structure has "empty"
changes -- turns out that information isn't relevant here, though we want it
in the parser.
Part of #89

Add mock data for CFR changes

---

notice_and_comment/static/regulations/css/less/comment-custom.less
notice_and_comment/static/regulations/css/less/module/header-custom.less

This changes the font weight on the tabs, the extra pixel on the tab borders, and the color on the sub-header mentioned in #97

fixes #97 changing font weight and width of tabs

---

manifest_base.yml

Celery only supports --option=value and not --option value or -option
value

Fix GNU-style command-line options

---

notice_and_comment/static/regulations/css/less/comment-custom.less

adds hover styles to read/write mode tabs
Is that double selector thing I did on Line#37 ok? It's to ensure the active tab doesn't get re-styled when hovered.

adding custom read/write mode tabs

---

notice_and_comment/settings/base.py

As discussed in #30, this configuration ensures that tasks aren't
considered finished in the event that a worker crashes or loses its
connection to the broker. In exchange for this behavior, we run a small
risk of duplicate submits.
[Resolves #30]

Configure celery to ack tasks on complete.

---

notice_and_comment/static/regulations/css/less/module/custom.less
notice_and_comment/static/regulations/css/less/module/note-custom.less

Per #52, N&C footnotes to match CFPB style.

Footnotes design styles

---

notice_and_comment/static/regulations/css/less/module/note-custom.less
notice_and_comment/templates/regulations/footnotes.html

Clicking the up arrow icon on footnotes will take the user back to the section they were on. #52

Footnotes - jump back links

---

notice_and_comment/static/regulations/css/less/comment-custom.less

unnecessary span style after changes in eregs/regulations-site#298

removing a span style

---

notice_and_comment/basic_auth.py
notice_and_comment/settings/base.py
notice_and_comment/settings/prod.py

Reuses the existing, relatively hardened HTTP AUTH comparisons from regcore.
Due to the loop back, we need to also set the AUTH info in API_BASE
Resolves #240.
I can imagine agencies wanting to add auth to only certain paths, but I don't think we need that flexibility in the near future.
Note, this will require everyone using the demo site (even just for data retrieval) add appropriate authentication. Please flag our dev channel before merging.

Add middleware for basic auth requirement

---

notice_and_comment/static/regulations/css/less/module/drawer-custom.less

There were a few pieces of the ToC drawer that didn't receive color overrides and looked out of place when the drawer was collapsed.

adding color overrides for some parts of the toc drawer

---

notice_and_comment/settings/base.py
notice_and_comment/settings/prod.py

- Use a file-based cache in dev environment
- Use redis in the prod environment

Use file-based cache for regs.gov lookups

---

manifest_dev.yml
manifest_prod.yml
newrelic.ini
notice_and_comment/__init__.py
notice_and_comment/celery.py
notice_and_comment/newrelic.py
notice_and_comment/wsgi.py
requirements.txt

* Add auto-generated new relic config
* Initialize new relic on app start and task queue start
Note: this initializes the new relic agent manually because the usual `newrelic run-program` invocation expects to find new relic creds in top-level environment variables, but ours live in cloud foundry user-provided services. I'm open to other approaches here, just haven't thought of anything less hacky.

Configure monitoring for webapp and task queue.

---

notice_and_comment/settings/base.py

In preparation for the not-yet-published rule, this creates _empty_ CFR
changes and a set of mock meta data. Eventually both should be derivable from
the `notice` structure. In the meantime, this will allow the parsed preamble
to display.
This also removes the "intro" content to  the 2016_02749 proposal, as we parse
that now. We'll need to follow up with a data update when this is merged.
For #239

Add 0000_0000 content; remove unneeded intro

---

notice_and_comment/__init__.py

Turns out this import is needed for the django app to pick up the celery
configuration.

Restore celery import.

---

notice_and_comment/static/regulations/css/less/comment-custom.less

Make sure Read and Write tab colors are correct, per #256
When hovering over Write tab:

Fix read/write tab colors

---

notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less

Update positioning of hero image on homepage so that it is always centered, addresses #268:

Homepage hero positioning

---

notice_and_comment/static/regulations/css/less/module/note-custom.less
notice_and_comment/templates/regulations/footnotes.html

* Remove outline on jump links to fix #181 
* Positioning hack for more accurate anchor positioning #180

Footnote fixes

---

notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less

- "Other ways to read and comment" collapsible section should have regular font:
- More padding under "About this tool" header

Homepage style tweaks

---

notice_and_comment/static/regulations/css/less/comment-custom.less
notice_and_comment/static/regulations/css/less/module/custom.less
notice_and_comment/static/regulations/css/less/module/drawer-custom.less
notice_and_comment/static/regulations/css/less/module/footer-custom.less
notice_and_comment/static/regulations/css/less/typography-custom.less
notice_and_comment/static/regulations/css/less/variables.less

fixes #159 
This is mostly just changing the `@blue` variable and then making some things that were using it incorrectly use the `@link_blue`
The header and tabs are now "mature blue"

new blues everywhere

---

notice_and_comment/templates/regulations/comment-additional-info.html

When the option that corresponds to the _instruction_ is selected in an
HTML select (or no option is selected), send an empty string back.

Send empty string on no selection

---

notice_and_comment/static/regulations/css/less/typography-custom.less

This updates the type hierarchy for N&C. 
There was a rule that was manually styling h3's that were `section-title`s but now that everything got shifted, I don't think it's needed anymore. There will be another PR In -site that will turn a bunch of `h3` into `h4` on some of the new sections we wrote (comment review, comment composition page) but it seems like these styles work appropriately for the algorithmically generated paragraphs/headers in the preamble.
This isn't playing nice with old eregs but wanted to get the PR up so other people could clone it.

WIP - updating type hierarchy

---

notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less

Remove negative z-index, more accurate positioning, and transparent background on `.hero` so the background hero image displays properly on environments like IE11.
Fixes #335

Fix homepage image

---

notice_and_comment/static/regulations/css/less/module/drawer-content-custom.less
notice_and_comment/static/regulations/css/less/variables.less

A semantically-named variable is now present in -site. Rather than making a
new variable in n&c, reuse that one.
Relies on eregs/regulations-site#382

Avoid defining a new variable

---

notice_and_comment/templates/regulations/comment-additional-info.html
notice_and_comment/templates/regulations/comment-disclaimer.html

Review your full comment:
- Comment additional info tabs (submitting on behalf of) now tab accessible
- Comment disclaimer show more/less toggles now tab accessible
Relies on: eregs/regulations-site#393

Set anchor tags for accessible tab navigation

---

manifest_base.yml

The cloud.gov Python buildpack attempts to `collectstatic` before all of the
environmental variables are set up (at least, that's how I'm interpreting a
deploy error). We used to default to `/tmp/static` or similar, but recently
removed that, which has negative security implications. As such, the
`collectstatic` issue is biting us.
This sets an environment variable which tells the buildpack to avoid
`collectstatic`ing -- we do it later in the deployment, anyway.

Avoid auto-collectstaticing when deploying

---

notice_and_comment/static/regulations/css/less/comment-custom.less
notice_and_comment/static/regulations/css/less/variables.less

Set section link underline, "Show", citation text, and upload attachment text colors.
Relies on: eregs/regulations-site#397
Fixes: eregs/notice-and-comment#354

Write mode polish

---

requirements.txt

I ran into an issue recently where I had a library version mismatch and
couldn't test attachments. Turns out, our requirements file was missing a few
updated libs.

Pin more library versions

---

notice_and_comment/static/regulations/css/less/module/custom.less
notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less
notice_and_comment/static/regulations/css/less/module/nc-homepage-media-queries-custom.less
notice_and_comment/templates/regulations/nc-homepage.html

Updated Homepage media queries for tablet/mobile view. #356 
**Tablet**
- 30px wide padding
**Mobile**
- set header text sizes
_Hero_
- top 30px padding
- left align text
- even out margins
- rule title 19px
_Read and Write_
- image margins
- other ways to comment text left aligned
- section bottom padding
_Build a good comment_
- smaller orange bullets
- section paddings
_About this tool_
- bottom padding
_Footer_
- align padding around text/logos

Homepage Mobile Polish

---

notice_and_comment/templates/regulations/main-header.html

Looks like:
Note that that citation is completely fictitious.

Add FR citation as title of non-prepub notices

---

notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less
notice_and_comment/templates/regulations/nc-homepage.html

In particular, text and icon changes for pre-publish and closed states
For #334 and #183
Looks like:

Tweak landing page for different notice states

---

notice_and_comment/static/regulations/css/less/module/header-custom.less
notice_and_comment/static/regulations/css/less/module/nc-homepage-custom.less
notice_and_comment/templates/regulations/main-header.html
notice_and_comment/templates/regulations/nc-homepage.html
notice_and_comment/templates/regulations/org-title.html

Fixes #369 and #372
- Mobile nav updated with partnership links
- Mobile nav trigger now working on homepage

Mobile Nav Update

---

deploy-travis.sh

This reduces the likelihood that deploy will timeout as less time is spent
within cloud.gov
For #339 
There's a soft dependency on eregs/regulations-site#379 ; merging this first won't break anything, it just won't be useful.

Fetch wkhtmltox from within travis

---

notice_and_comment/static/regulations/css/less/comment-custom.less
notice_and_comment/static/regulations/css/less/variables.less

- Darker "Write comment" colors for accessible contrast ratio.
- Lighter gray on Write mode excerpt toggle bar.
_also removed some unused styles_
#377 
---

Color contrast updates

---

README.md
manifest_dev.yml
notice_and_comment/settings/base.py

We want to drop auth on our sites, but may want to turn it on selectively in
the future.

Allow whole-site auth to be configured via env var

---

manifest_dev.yml

We don't want the demo site indexable. We don't _currently_ want prod
indexable, so its manifest isn't being updated.

Disable robots on demo

---

compliance/component.yaml
opencontrol.yaml

Initial documentation for our controls -- used in the ATO.

Initial OpenControl Docs

---

compliance/component.yaml

This patch will fix the reading problems so that masonry can use it to
autogenerate docs
After using this patch, a user can then run:
```bash
$ compliance-masonry get
$ compliance-masonry docs gitbook LATO
$ cd exports
$ gitbook serve #you'll need gitbook installed
```

Fix masonry issues for compliance yaml

---

notice_and_comment/templates/regulations/nc-homepage.html

This updates a link to 18F and to the eRegs homepage to be `https://`, since they both work properly over each of them.

Adding HTTPS to a couple of links

---

notice_and_comment/static/regulations/css/scss/_variables.scss
notice_and_comment/static/regulations/css/scss/module/_nc-homepage-custom.scss
notice_and_comment/static/regulations/css/scss/module/_note-custom.scss

I left the variables required to power the homepage in this repo, however, one of the variables shared the same name as something  in -site but with a different hex value. Renamed so there is no conflict.

changing gray variable

---

.travis.yml

This didn't show up in our earlier tests because we were pointing to the
non-SASS version of -site.

Install SASS in travis

---

notice_and_comment/settings/prod.py

Also removes redundant `os.environ` calls; the cfenv library does that for us
For 18F/eregs-platform#36

Allow comment id to come from cups

---

notice_and_comment/urls.py

The home page makes a large number of API requests; without caching, it'll
spin those off for every user
Depends on eregs/regulations-site#454

Add caching to home page

---

notice_and_comment/nc_caches.py
notice_and_comment/urls.py

First-pass attempt to fix the incorrect “days remaining” display.

Remove all homepage caching

---

requirements.txt

We have been using "master" for both regulations libraries. This pins both to
versions associated with the current master.
This won't ever need to be deployed in production, but best to pin now.

Update Django, pin regulations

---

notice_and_comment/settings/prod.py

Per [Cloud Foundry documentation](https://docs.cloudfoundry.org/running/apps-enable-diego.html#app-code) use of `$VCAP_APP_HOST` and `$VCAP_APP_PASSWORD` are incompatible with newer (Diego-based) Cloud Foundry deployments. This change makes this repository forward compatible with the new cloud.gov environment deployment in AWS GovCloud.

Cloud Foundry forward-compatibility
